version: '3.8'

services:
  # Auth Service with 2 instances
  auth-service2-1:
    image: dockerzionjiam/reviseme-auth-service2-1:latest
    ports:
      - "5002"  # Expose on internal port only
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/testDB
    depends_on:
      - mongo
    networks:
      - app-network

  auth-service2-2:
    image: dockerzionjiam/reviseme-auth-service2-2:latest
    ports:
      - "5003"  # Expose on internal port only
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/testDB
    depends_on:
      - mongo
    networks:
      - app-network

  # Flashcard Service with 2 instances
  flashcard-service-1:
    image: dockerzionjiam/flashcardservice-1:latest
    ports:
      - "5001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/testDB
    depends_on:
      - mongo
    networks:
      - app-network

  flashcard-service-2:
    image: dockerzionjiam/flashcardservice-2:latest
    ports:
      - "5004"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/testDB
    depends_on:
      - mongo
    networks:
      - app-network

  # Flashcard AI Service with 2 instances
  flashcard-ai-service-1:
    image: dockerzionjiam/reviseme-flashcard-ai-service-1:latest
    ports:
      - "5010"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/testDB
    depends_on:
      - mongo
    networks:
      - app-network

  flashcard-ai-service-2:
    image: dockerzionjiam/reviseme-flashcard-ai-service-2:latest
    ports:
      - "5011"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/testDB
    depends_on:
      - mongo
    networks:
      - app-network

  # MongoDB
  mongo:
    image: dockerzionjiam/mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # Frontend
  frontend:
    image: dockerzionjiam/reviseme-frontend:latest
    ports:
      - "3000:80"
    networks:
      - app-network

  # NGINX Load Balancer
  nginx:
    image: dockerzionjiam/reviseme-nginx-1:latest
    ports:
      - "8080:80"  # Expose port 80 for load balancing
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the NGINX configuration
    depends_on:
      - auth-service2-1
      - auth-service2-2
      - flashcard-service-1
      - flashcard-service-2
      - flashcard-ai-service-1
      - flashcard-ai-service-2
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge